---
# tasks file for caranova.base_os
- name: dnf update -y
  dnf:
    name: '*'
    state: latest

# TODO insert handler ensuring update is called at least and at most once in this play
- name: ensure mothership packages are installed
  dnf:
    name: '{{ packages }}'
    state: present

- name: remove docker from premises
  dnf: docker
  state: absent

- name: grab the dotfiles when they exist one day
  debug:
      # TODO grab i3 polybar, gaps soundicon
      msg: "Grab wm and other stuff"  # not required. The customized message that is printed. If omitted, prints a generic message.
      var: undefined # not required. A variable name to debug.  Mutually exclusive with the 'msg' option.
      verbosity: 0 # not required. A number that controls when the debug is run, if you set to 3 it will only run debug when -vvv or above