# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/fedora-31"
  end

    config.vm.provider :virtualbox do |v|
      #v.name = "epsilon.dev"
      v.memory = 2048
      v.cpus = 1
    end

    config.vm.provision :ansible do |ansible|
      ansible.verbose = "vvv"
      ansible.playbook = "site.yml"
    end
 end